services:
  dho-api:
    build: .
    container_name: dho-api
    ports:
      - "${PORT:-8090}:8090"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - UPLOAD_DIR=${UPLOAD_DIR}
    volumes:
      - ./uploads:/app/${UPLOAD_DIR:-uploads}
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
