spring.application.name=dho-api

# MariaDB DHO_Application Configuration
spring.datasource.url=jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Server
server.port=8090


# Upload Configuration
upload.dir=${UPLOAD_DIR:uploads}

# Swagger UI / OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.display-request-duration=true
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=br.com.sebratel.bff.dho.controller



# Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
